#!/bin/bash

cd ./hash-files
cargo build --release
cd ..

cd ./wordle/bin-wordle-wasm
./publish
cd ../..
./hash-files/target/release/hash-files ./publish/wordle-analyze ./publish/wordle-analyze/service-worker.js

cd ./wordle/diy
./publish
cd ../..
./hash-files/target/release/hash-files ./publish/wordle-diy ./publish/wordle-diy/service-worker.js
