#!/bin/bash

cd ./hash-files
cargo build --release
cd ..

cd ./wordle/bin-wordle-wasm
./publish
cd ../..
./hash-files/target/release/hash-files ./publish/wordle-analyze ./publish/wordle-analyze/service-worker.js

cd ./wordle/v1
./publish
cd ../..
./hash-files/target/release/hash-files ./publish/wordle-v1 ./publish/wordle-v1/service-worker.js
