#!/bin/bash
DEST=~/Code/blog/static/wordle-analyze

wasm-pack build --target web

mkdir -p $DEST/data
cp "../data/2315/answers.txt" "$DEST/data/answers.txt"
cp "../data/2315/valid.txt" "$DEST/data/valid.txt"
cp "../data/v12.txt" "$DEST/data/v12.txt"

mkdir -p $DEST/pkg
cp "pkg/wordle_wasm_bg.wasm" "$DEST/pkg/wordle_wasm_bg.wasm"
cp "pkg/wordle_wasm.js" "$DEST/pkg/wordle_wasm.js"

cp app.webmanifest "$DEST/app.webmanifest"
cp index.html "$DEST/index.html"
cp service-worker.js "$DEST/service-worker.js"
cp wordle-analyze-a.png "$DEST/wordle-analyze-a.png"

echo Run: sd blog deploy